security:
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: username

  firewalls:
    main:
      pattern: ^/
      lazy: true
      form_login:
        login_path: login
        check_path: login_check
      access_denied_handler: App\Security\AccessDeniedHandler
