security:
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: username

  firewalls:
    main:
      pattern: ^/
      lazy: true
      form_login:
        login_path: login
        check_path: login_check
      access_denied_handler: App\Security\AccessDeniedHandler

  access_control:
    - { path: ^/login, roles: PUBLIC_ACCESS }
    - { path: ^/login/validate, roles: PUBLIC_ACCESS }
    - { path: ^/users, roles: ROLE_USER }
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/user, roles: ROLE_USER }
